issues:
  exclude-use-default: false

linters:
  disable-all: true
  enable:
    - cyclop
    - deadcode
    - goconst
    - godot
    - godox
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - typecheck
    - unconvert
    - varcheck
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 16
