issues:
  exclude-use-default: false
  exclude-rules:
    - text: "G101: Potential hardcoded credentials"
      path: "internal/admin/handler/handler_test"
      linters:
        - gosec
    - text: "G107: Potential HTTP request made with variable url"
      path: "internal/admin/service/registration.go"
      linters:
        - gosec

linters:
  disable-all: true
  enable:
    - cyclop
    - deadcode
    - goconst
    - godot
    - godox
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - typecheck
    - unconvert
    - varcheck
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 16
  goimports:
    local-prefixes: github.com/devpies/saas-core