linters:
  enable:
    - revive
    - cyclop

# The list of ids of default excludes to include or disable. By default it's empty.
issues:
  include:
    - EXC0012 # disable excluding of issues about comments from revive

linters-settings:
  revive:
    ignore-generated-header: false
    enable-all-rules: true
    severity: warning
    confidence: 0.8
    errorCode: 0
    warningCode: 0
    rules:
      # Recommended in Revive docs
      # https://github.com/mgechev/revive#recommended-configuration

      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      # Custom
      - name: struct-tag
      - name: early-return
      - name: defer
  cyclop:
    max-complexity: 15