apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-project-test
spec:
  selector:
    matchLabels:
      app: db-project-test
  template:
    metadata:
      labels:
        app: db-project-test
    spec:
      containers:
        - name: db-project-test
          image: postgres:11.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: POSTGRES_DB
              value: project_test
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: db-project-test-svc
spec:
  type: NodePort
  selector:
    app: db-project-test
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30019