apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-user-sessions-depl
spec:
  selector:
    matchLabels:
      app: db-user-sessions
  template:
    metadata:
      labels:
        app: db-user-sessions
    spec:
      volumes:
        - name: db-user-sessions-volume
          hostPath:
            path: "/Users/ivorscott/DevPie/core/data/sessions"
      containers:
        - name: db-user-sessions
          image: postgres:11.6
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-user-sessions-volume
---
apiVersion: v1
kind: Service
metadata:
  name: db-user-sessions-svc
spec:
  type: NodePort
  selector:
    app: db-user-sessions
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      nodePort: 30007