apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/registration
            pathType: Prefix
            backend:
              service:
                name: mic-registration-svc
                port:
                  number: 4001
          - path: /api/users
            pathType: Prefix
            backend:
              service:
                name: users-svc
                port:
                  number: 4005
          - path: /api/projects
            pathType: Prefix
            backend:
              service:
                name: projects-svc
                port:
                  number: 4004
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mic-admin-svc
                port:
                  number: 4000
