apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-registration
spec:
  selector:
    matchLabels:
      app: mic-registration
  template:
    metadata:
      labels:
        app: mic-registration
    spec:
      containers:
        - image: registration:latest
          name: mic-registration
          ports:
            - containerPort: 4001
          env:
            - name: REGISTRATION_WEB_PORT
              value: "4001"
            - name: REGISTRATION_WEB_ADDRESS
              value: "http://localhost"

            - name: REGISTRATION_COGNITO_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: cognito_app_client_id
            - name: REGISTRATION_COGNITO_USER_POOL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: cognito_user_pool_client_id
            - name: REGISTRATION_COGNITO_REGION
              value: "eu-central-1"
---
apiVersion: v1
kind: Service
metadata:
  name: mic-registration-svc
spec:
  selector:
    app: mic-registration
  ports:
    - port: 4001
      targetPort: 4001