apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-user
spec:
  selector:
    matchLabels:
      app: mic-user
  template:
    metadata:
      labels:
        app: mic-user
    spec:
      containers:
        - image: user:latest
          name: mic-user
          ports:
            - containerPort: 4005
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"

            - name: USER_WEB_PORT
              value: "4005"
            - name: USER_WEB_ADDRESS
              value: "http://localhost"

            - name: USER_COGNITO_SHARED_USER_POOL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: cognito_shared_user_pool_client_id
            - name: USER_COGNITO_REGION
              value: "eu-central-1"

            - name: USER_NATS_ADDRESS
              value: "nats-svc"
            - name: USER_NATS_PORT
              value: "4222"

            - name: USER_DB_USER
              value: postgres
            - name: USER_DB_PASSWORD
              value: postgres
            - name: USER_DB_HOST
              value: db-user-svc
            - name: USER_DB_PORT
              value: "5432"
            - name: USER_DB_NAME
              value: user
            - name: USER_DB_DISABLE_TLS
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: mic-user-svc
spec:
  selector:
    app: mic-user
  ports:
    - port: 4005
      targetPort: 4005