apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-registration
spec:
  selector:
    matchLabels:
      app: mic-registration
  template:
    metadata:
      labels:
        app: mic-registration
    spec:
      containers:
        - image: registration:latest
          name: mic-registration
          ports:
            - containerPort: 4001
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"

            - name: REGISTRATION_WEB_PORT
              value: "4001"
            - name: REGISTRATION_WEB_ADDRESS
              value: "http://localhost"

            - name: REGISTRATION_COGNITO_USER_POOL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: cognito_user_pool_client_id
            - name: REGISTRATION_COGNITO_SHARED_USER_POOL_CLIENT_ID
              valueFrom:
               secretKeyRef:
                 name: secrets
                 key: cognito_shared_user_pool_client_id
            - name: REGISTRATION_COGNITO_REGION
              value: "eu-central-1"

            - name: REGISTRATION_DYNAMODB_TENANT_TABLE
              value: tenants
            - name: REGISTRATION_DYNAMODB_AUTH_TABLE
              value: auth-info
            - name: REGISTRATION_DYNAMODB_CONFIG_TABLE
              value: silo-config

            - name: REGISTRATION_NATS_ADDRESS
              value: "nats-svc"
            - name: REGISTRATION_NATS_PORT
              value: "4222"
---
apiVersion: v1
kind: Service
metadata:
  name: mic-registration-svc
spec:
  selector:
    app: mic-registration
  ports:
    - port: 4001
      targetPort: 4001