apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-tenant
spec:
  selector:
    matchLabels:
      app: mic-tenant
  template:
    metadata:
      labels:
        app: mic-tenant
    spec:
      containers:
        - image: tenant:latest
          name: mic-tenant
          ports:
            - containerPort: 4002
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: aws_access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"

            - name: TENANT_WEB_PORT
              value: "4002"
            - name: TENANT_WEB_ADDRESS
              value: "http://localhost"

            - name: TENANT_COGNITO_USER_POOL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: cognito_user_pool_client_id
            - name: TENANT_COGNITO_REGION
              value: "eu-central-1"

            - name: TENANT_DYNAMODB_TENANT_TABLE
              value: tenants
            - name: TENANT_DYNAMODB_AUTH_TABLE
              value: auth-info
            - name: TENANT_DYNAMODB_CONFIG_TABLE
              value: silo-config

            - name: TENANT_NATS_ADDRESS
              value: "nats-svc"
            - name: TENANT_NATS_PORT
              value: "4222"
---
apiVersion: v1
kind: Service
metadata:
  name: mic-tenant-svc
spec:
  selector:
    app: mic-tenant
  ports:
    - port: 4002
      targetPort: 4002