apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-projects-depl
spec:
  selector:
    matchLabels:
      app: mic-projects
  template:
    metadata:
      labels:
        app: mic-projects
    spec:
      containers:
        - image: devpies/projects:latest
          name: mic-projects
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: API_WEB_PORT
              value: ":4000"
            - name: API_WEB_CORS_ORIGINS
              value: "http://localhost:3000, https://devpie.local:3000"
            - name: API_DB_USER
              value: postgres
            - name: API_DB_NAME
              value: postgres
            - name: API_DB_PASSWORD
              value: postgres
            - name: API_DB_HOST
              value: mic-db-projects-svc
            - name: API_DB_DISABLE_TLS
              value: "true"
      initContainers:
        - name: schema-migration
          image: devpies/projects-migration:v000001
          env:
            - name: DB_URL
              value: postgresql://postgres:postgres@mic-db-projects-svc:5432/postgres?sslmode=disable
          command: ["migrate"]
          args:
            ["-path", "/migrations", "-verbose", "-database", "$(DB_URL)", "up"]
---
apiVersion: v1
kind: Service
metadata:
  name: mic-projects-svc
spec:
  selector:
    app: mic-projects
  ports:
    - port: 4020
      targetPort: 4000
