name: admin

on:
  push:
    paths:
      - ".github/workflows/admin.yaml"
      - "cmd/admin/**"
      - "internal/admin/**"
      - "deploy/admin.dockerfile"
      - ".github/workflows/reusable.yaml"
      - "go.*"
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable.yaml
    with:
      service: admin
    secrets:
      token: ${{ secrets.PAT }}