name: project

on:
  push:
    paths:
      - ".github/workflows/project.yaml"
      - "cmd/project/**"
      - "internal/project/**"
      - "deploy/project.dockerfile"
      - "go.*"
  workflow_dispatch:

jobs:
  buildAndDeploy:
    uses: devpies/saas-core/.github/workflows/reusable.yaml@main
    secrets:
      envPAT: ${{ secrets.PAT }} # pass just this secret