name: project

on:
  push:
    paths:
      - ".github/workflows/project.yaml"
      - "cmd/project/**"
      - "internal/project/**"
      - "deploy/project.dockerfile"
      - ".github/workflows/reusable.yaml"
      - "go.*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0

      - uses: actions/checkout@v2

      - name: Deploy manifest
        run: |
          kubectl apply -f ./manifests/db-project-test.yaml
          sleep 5
           kubectl port-forward deploy/db-project-test 5432:5432 &>/dev/null &
          sleep 5
           kubectl port-forward deploy/db-project-test 5432:5432 &>/dev/null &
      - name: Run Tests
        run: |
          make project-test project-db-test-port=5432 -- -v
  reuse:
    needs: test
    uses: ./.github/workflows/reusable.yaml
    with:
      service: project
    secrets:
      token: ${{ secrets.PAT }}