name: project

on:
  push:
    paths:
      - ".github/workflows/project.yaml"
      - "cmd/project/**"
      - "internal/project/**"
      - "deploy/project.dockerfile"
      - "go.*"
  workflow_dispatch:

jobs:
  buildAndDeploy:
    uses: ./.github/workflows/reusable.yaml
    secrets:
      PAT: ${{ secrets.PAT }}