name: project

on:
  push:
    paths:
      - ".github/workflows/project.yaml"
      - "cmd/project/**"
      - "internal/project/**"
      - "deploy/project.dockerfile"
      - ".github/workflows/reusable.yaml"
      - "go.*"
  workflow_dispatch:

jobs:
  buildAndDeploy:
    uses: ./.github/workflows/reusable.yaml
    with:
      service: project
    secrets:
      token: ${{ secrets.PAT }}