name: project

on:
  push:
    paths:
      - ".github/workflows/project.yaml"
      - "cmd/project/**"
      - "internal/project/**"
      - "deploy/project.dockerfile"
      - ".github/workflows/reusable.yaml"
      - "go.*"
  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0
      - uses: actions/checkout@v2
      - name: Deploy manifest
        run: kubectl apply -f ./manifests/db-project-test.yaml
      - name: Debug
        run: |
          kubectl get svc
          kubectl describe svc db-project-test-svc
          kubectl get deploy
          kubectl describe deploy db-project-test
          kubectl get events --sort-by='{.lastTimestamp}'
      - name: Run Tests
        run: make project-test
  buildAndDeploy:
    uses: ./.github/workflows/reusable.yaml
    with:
      service: project
    secrets:
      token: ${{ secrets.PAT }}