name: registration

on:
  push:
    paths:
      - ".github/workflows/registration.yaml"
      - "cmd/registration/**"
      - "internal/registration/**"
      - "deploy/registration.dockerfile"
      - ".github/workflows/reusable.yaml"
      - "go.*"
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable.yaml
    with:
      service: registration
    secrets:
      token: ${{ secrets.PAT }}