name: registration

on:
  push:
    paths:
      - ".github/workflows/registration.yaml"
      - "cmd/registration/**"
      - "internal/registration/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        env:
          IMAGE: registration
          OWNER: ${{ github.repository_owner }}
        run: |
          export SHA=$(git rev-parse --short HEAD)

          docker build \
          --build-arg GITHUB_USER=${{ secrets.USERNAME }} \
          --build-arg GITHUB_TOKEN=${{ secrets.PAT }} --file ./deploy/registration.dockerfile --tag ghcr.io/$OWNER/$IMAGE:$SHA .

          docker push ghcr.io/$OWNER/$IMAGE:$SHA

          echo $OWNER/$IMAGE:$SHA > .build-version

          cat > patch.sh <<EOF
          #!/bin/bash
          sed -i 's/$IMAGE:.*/$IMAGE:$SHA/' $IMAGE.yaml
          EOF

          chmod +x patch.sh

      - uses: actions/checkout@v2
        with:
          repository: devpies/saas-infra
          token: ${{ secrets.PAT }}
          path: saas-infra
      - run: |
          mv patch.sh saas-infra/manifests
          cd saas-infra/manifests

          ./patch.sh
          rm patch.sh

          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git add .
          export VERSION=$(cat .build-version)
          git commit -m "new release: $VERSION"
          git push