name: subscription

on:
  push:
    paths:
      - ".github/workflows/subscription.yaml"
      - "cmd/subscription/**"
      - "internal/subscription/**"
      - "deploy/subscription.dockerfile"
      - ".github/workflows/reusable.yaml"
      - "go.*"
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable.yaml
    with:
      service: subscription
    secrets:
      token: ${{ secrets.PAT }}