name: user

on:
  push:
    paths:
      - ".github/workflows/user.yaml"
      - "cmd/user/**"
      - "internal/user/**"
      - "deploy/user.dockerfile"
      - ".github/workflows/reusable.yaml"
      - "go.*"
  workflow_dispatch:

jobs:
  buildAndDeploy:
    uses: ./.github/workflows/reusable.yaml
    with:
      service: user
    secrets:
      token: ${{ secrets.PAT }}